/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iglnierod.gamearchive.view.home.list;

import com.iglnierod.gamearchive.view.home.list.panel.ListPreviewPanel;
import java.awt.event.MouseListener;

/**
 *
 * @author iglnierod
 */
public class ListsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListsPanel
     */
    public ListsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerScrollPane = new javax.swing.JScrollPane();
        centerPanel = new javax.swing.JPanel();
        createListPanel = new com.iglnierod.gamearchive.view.home.list.panel.CreateListPanel();

        setLayout(new java.awt.BorderLayout());

        centerScrollPane.setBorder(null);

        centerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        centerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20));
        centerPanel.add(createListPanel);

        centerScrollPane.setViewportView(centerPanel);

        add(centerScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void addCreateListPanelMouseListener(MouseListener listener) {
        this.createListPanel.addMouseListener(listener);
        this.createListPanel.addMouseListeners(listener);
    }
    
    public void addList(ListPreviewPanel list) {
        this.centerPanel.add(list);
        this.centerPanel.revalidate();
        this.centerPanel.repaint();
    }
    
    public void emptyListPanel() {
        this.centerPanel.removeAll();
        this.centerPanel.add(createListPanel);
        this.centerPanel.revalidate();
        this.centerPanel.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JScrollPane centerScrollPane;
    private com.iglnierod.gamearchive.view.home.list.panel.CreateListPanel createListPanel;
    // End of variables declaration//GEN-END:variables
}
