/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iglnierod.gamearchive.view.home.list;

import com.iglnierod.gamearchive.view.home.list.panel.ListPreviewPanel;
import com.iglnierod.gamearchive.view.layout.WrapLayout;
import java.awt.FlowLayout;
import java.awt.event.MouseListener;

/**
 *
 * @author iglnierod
 */
public class ListsPanel extends javax.swing.JPanel {

    private boolean isUserProfile;

    /**
     * Creates new form ListsPanel
     */
    public ListsPanel(boolean isUserProfile) {
        this.isUserProfile = isUserProfile;
        initComponents();
        this.createListPanel.setVisible(!this.isUserProfile);
        this.centerPanel.setLayout(new WrapLayout(FlowLayout.LEFT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerScrollPane = new javax.swing.JScrollPane();
        centerPanel = new javax.swing.JPanel();
        createListPanel = new com.iglnierod.gamearchive.view.home.list.panel.CreateListPanel();
        favouriteListPanel = new com.iglnierod.gamearchive.view.home.list.panel.FavouriteListPanel();

        setLayout(new java.awt.BorderLayout());

        centerScrollPane.setBorder(null);

        centerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(favouriteListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(856, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(favouriteListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(446, Short.MAX_VALUE))
        );

        centerScrollPane.setViewportView(centerPanel);

        add(centerScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void addCreateListPanelMouseListener(MouseListener listener) {
        this.createListPanel.addMouseListener(listener);
        this.createListPanel.addMouseListeners(listener);
    }

    public void addFavouriteListPanelMouseListener(MouseListener l) {
        this.favouriteListPanel.addMouseListener(l);
        this.favouriteListPanel.addMouseListeners(l);
    }

    public void addList(ListPreviewPanel list) {
        this.centerPanel.add(list);
        this.centerPanel.revalidate();
        this.centerPanel.repaint();
    }

    public void emptyListPanel() {
        this.centerPanel.removeAll();
        if (!isUserProfile) {
            this.centerPanel.add(createListPanel);
        }
        this.centerPanel.add(favouriteListPanel);
        this.centerPanel.revalidate();
        this.centerPanel.repaint();
    }

    public boolean isIsUserProfile() {
        return isUserProfile;
    }

    public void setIsUserProfile(boolean isUserProfile) {
        this.isUserProfile = isUserProfile;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JScrollPane centerScrollPane;
    private com.iglnierod.gamearchive.view.home.list.panel.CreateListPanel createListPanel;
    private com.iglnierod.gamearchive.view.home.list.panel.FavouriteListPanel favouriteListPanel;
    // End of variables declaration//GEN-END:variables
}
