/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.iglnierod.gamearchive.view.home.dialog;

import com.iglnierod.gamearchive.view.layout.WrapLayout;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.event.ActionListener;
import javax.swing.JComponent;

/**
 *
 * @author iglnierod
 */
public class WhatToPlayDialog extends javax.swing.JDialog {

    /**
     * Creates new form WhatToPlayDialog
     */
    public WhatToPlayDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.genresPanel.setLayout(new WrapLayout(FlowLayout.LEFT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        platfomsButtonGroup = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        genresPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        minRatingLabel = new javax.swing.JLabel();
        minRatingSpinner = new javax.swing.JSpinner();
        ownedPlatformsRadioButton = new javax.swing.JRadioButton();
        allPlatformsRadioButton = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        getGameButton = new javax.swing.JButton();
        resultPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GameArchive - WhatToPlay");

        titleLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("What To Play");

        descriptionLabel.setFont(new java.awt.Font("Liberation Sans", 2, 14)); // NOI18N
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText("Get a random game depending on what you choose");

        genresPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Genres"));
        genresPanel.setMaximumSize(new java.awt.Dimension(500, 200));
        genresPanel.setMinimumSize(new java.awt.Dimension(500, 200));
        genresPanel.setPreferredSize(new java.awt.Dimension(500, 200));
        jPanel2.add(genresPanel);

        minRatingLabel.setText("Minimun Rating");
        jPanel4.add(minRatingLabel);

        minRatingSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 10));
        jPanel4.add(minRatingSpinner);

        platfomsButtonGroup.add(ownedPlatformsRadioButton);
        ownedPlatformsRadioButton.setSelected(true);
        ownedPlatformsRadioButton.setText("Owned platforms");
        jPanel4.add(ownedPlatformsRadioButton);

        platfomsButtonGroup.add(allPlatformsRadioButton);
        allPlatformsRadioButton.setText("All platforms");
        jPanel4.add(allPlatformsRadioButton);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMaximumSize(new java.awt.Dimension(50, 10));
        jPanel4.add(jSeparator2);

        getGameButton.setText("Get Game");
        jPanel3.add(getGameButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(descriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(resultPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel)
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void addGetGameButtonActionListener(ActionListener l) {
        this.getGameButton.addActionListener(l);
    }

    public void addGenre(JComponent component) {
        this.genresPanel.add(component);
    }

    public void addGameResult(JComponent component) {
        this.resultPanel.add(component);
        revalidate();
        repaint();
    }

    public Component[] getGenresPanelComponents() {
        return this.genresPanel.getComponents();
    }

    public int getMinRatingSpinnerValue() {
        return (int) this.minRatingSpinner.getValue();
    }
    
    public boolean isAllPlatformsSelected() {
        return this.allPlatformsRadioButton.isSelected();
    }
    
    public void emptyResultPanel() {
        this.resultPanel.removeAll();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allPlatformsRadioButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JPanel genresPanel;
    private javax.swing.JButton getGameButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel minRatingLabel;
    private javax.swing.JSpinner minRatingSpinner;
    private javax.swing.JRadioButton ownedPlatformsRadioButton;
    private javax.swing.ButtonGroup platfomsButtonGroup;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
