/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.iglnierod.gamearchive.view.game;

import javax.swing.ImageIcon;
import javax.swing.JToggleButton;

/**
 *
 * @author iglnierod
 */
public class GameDialog extends javax.swing.JDialog {

    /**
     * Creates new form GameDialog
     */
    public GameDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelToggleButton = new javax.swing.JToggleButton();
        centerPanel = new javax.swing.JPanel();
        coverLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        genresPanel = new javax.swing.JPanel();
        ratingProgressBar = new javax.swing.JProgressBar();
        ratingNumberLabel = new javax.swing.JLabel();
        maximumRatingLabel = new javax.swing.JLabel();
        ratingCountLabel = new javax.swing.JLabel();
        platformsTitleLabel = new javax.swing.JLabel();
        platformsPanel = new javax.swing.JPanel();
        genresTitleLabel = new javax.swing.JLabel();

        modelToggleButton.setText("XBOX");
        modelToggleButton.setToolTipText("");
        modelToggleButton.setActionCommand("");
        modelToggleButton.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        coverLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/t_cover_big.jpg"))); // NOI18N

        nameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        nameLabel.setText("Hollow Knigth");

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setForeground(new java.awt.Color(255, 255, 255));
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setText("A 2D metroidvania with an emphasis on close combat and exploration in which the player enters the once-prosperous now-bleak insect kingdom of Hallownest, travels through its various districts, meets friendly inhabitants, fights hostile ones and uncovers the kingdom's history while improving their combat abilities and movement arsenal by fighting bosses and accessing out-of-the-way areas.");
        descriptionTextArea.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        descriptionTextArea.setEnabled(false);
        jScrollPane1.setViewportView(descriptionTextArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                .addContainerGap())
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(coverLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        genresPanel.setMaximumSize(new java.awt.Dimension(168, 32767));
        genresPanel.setMinimumSize(new java.awt.Dimension(168, 34));
        genresPanel.setPreferredSize(new java.awt.Dimension(168, 120));

        ratingProgressBar.setValue(50);

        ratingNumberLabel.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        ratingNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ratingNumberLabel.setText("80.5");

        maximumRatingLabel.setFont(new java.awt.Font("Liberation Sans", 2, 14)); // NOI18N
        maximumRatingLabel.setText("/100");

        ratingCountLabel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        ratingCountLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group_24dp.png"))); // NOI18N
        ratingCountLabel.setText("5232");

        platformsTitleLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        platformsTitleLabel.setText("Platforms");

        platformsPanel.setMaximumSize(new java.awt.Dimension(168, 32767));
        platformsPanel.setMinimumSize(new java.awt.Dimension(168, 34));
        platformsPanel.setPreferredSize(new java.awt.Dimension(168, 120));

        genresTitleLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        genresTitleLabel.setText("Genres");

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, westPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, westPanelLayout.createSequentialGroup()
                        .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ratingCountLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ratingProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, westPanelLayout.createSequentialGroup()
                        .addComponent(ratingNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maximumRatingLabel)
                        .addGap(54, 54, 54))))
            .addGroup(westPanelLayout.createSequentialGroup()
                .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(platformsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genresPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(westPanelLayout.createSequentialGroup()
                        .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(westPanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(platformsTitleLabel))
                            .addGroup(westPanelLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(genresTitleLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingNumberLabel)
                    .addComponent(maximumRatingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratingCountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(platformsTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(platformsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(genresTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genresPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(196, 196, 196))
        );

        getContentPane().add(westPanel, java.awt.BorderLayout.EAST);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setNameLabelText(String name) {
        this.nameLabel.setText(name);
        this.nameLabel.setToolTipText(name);
    }

    public void setCoverLabelIcon(ImageIcon cover) {
        this.coverLabel.setIcon(cover);
    }

    public void setSummaryTextArea(String description) {
        this.descriptionTextArea.setText(description);
    }

    public void setRatingProgressBar(int rating) {
        this.ratingProgressBar.setValue(rating);
        this.ratingNumberLabel.setText(String.valueOf(rating));
    }

    public void setRatingCountLabel(int ratingCount) {
        this.ratingCountLabel.setText(String.valueOf(ratingCount));
    }

    public void addPlatformToggleButton(String platformName) {
        JToggleButton platform = new JToggleButton(platformName);
        platform.setEnabled(false);
        platformsPanel.add(platform);
        platformsPanel.revalidate();
    }

    public void addGenreToggleButton(String genreName) {
        JToggleButton genre = new JToggleButton(genreName);
        genre.setEnabled(false);
        genresPanel.add(genre);
        genresPanel.revalidate();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel coverLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JPanel genresPanel;
    private javax.swing.JLabel genresTitleLabel;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maximumRatingLabel;
    private javax.swing.JToggleButton modelToggleButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel platformsPanel;
    private javax.swing.JLabel platformsTitleLabel;
    private javax.swing.JLabel ratingCountLabel;
    private javax.swing.JLabel ratingNumberLabel;
    private javax.swing.JProgressBar ratingProgressBar;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables
}
