/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package com.iglnierod.gamearchive.view.game;

import javax.swing.JLabel;

/**
 *
 * @author iglnierod
 */
public class GameCoverLabel extends JLabel {

    /**
     * Creates new form GameCoverPreview
     */
    public GameCoverLabel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(90, 128));
        setMinimumSize(new java.awt.Dimension(90, 128));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(90, 128));
        setRequestFocusEnabled(false);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
