/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iglnierod.gamearchive.view.home.search;

import java.awt.Component;
import java.awt.event.ActionListener;

/**
 *
 * @author iglnierod
 */
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     */
    public SearchPanel() {
        initComponents();
        this.filtersPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        searchEastPanel = new javax.swing.JPanel();
        searchWestPanel = new javax.swing.JPanel();
        filterButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultPanel = new javax.swing.JPanel();
        filtersPanel = new com.iglnierod.gamearchive.view.home.search.FiltersPanel();

        setLayout(new java.awt.BorderLayout());

        northPanel.setPreferredSize(new java.awt.Dimension(1200, 45));
        northPanel.setLayout(new java.awt.BorderLayout());

        searchEastPanel.setMaximumSize(new java.awt.Dimension(120, 50));
        searchEastPanel.setMinimumSize(new java.awt.Dimension(120, 50));
        searchEastPanel.setPreferredSize(new java.awt.Dimension(120, 50));
        searchEastPanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout searchEastPanelLayout = new javax.swing.GroupLayout(searchEastPanel);
        searchEastPanel.setLayout(searchEastPanelLayout);
        searchEastPanelLayout.setHorizontalGroup(
            searchEastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        searchEastPanelLayout.setVerticalGroup(
            searchEastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        northPanel.add(searchEastPanel, java.awt.BorderLayout.EAST);

        searchWestPanel.setMaximumSize(new java.awt.Dimension(120, 50));
        searchWestPanel.setMinimumSize(new java.awt.Dimension(120, 50));
        searchWestPanel.setPreferredSize(new java.awt.Dimension(120, 50));
        searchWestPanel.setRequestFocusEnabled(false);

        filterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/round_tune_white_24dp.png"))); // NOI18N
        filterButton.setText("Filter");
        filterButton.setToolTipText("Filter search");
        filterButton.setMaximumSize(new java.awt.Dimension(90, 32));
        filterButton.setMinimumSize(new java.awt.Dimension(90, 32));
        filterButton.setPreferredSize(new java.awt.Dimension(90, 32));
        searchWestPanel.add(filterButton);

        northPanel.add(searchWestPanel, java.awt.BorderLayout.WEST);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 50));

        searchTextField.setColumns(20);
        searchTextField.setToolTipText("");
        searchTextField.setPreferredSize(new java.awt.Dimension(274, 28));
        jPanel1.add(searchTextField);

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/round_search_white_24dp.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.setToolTipText("Search");
        jPanel1.add(searchButton);

        northPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(northPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setPreferredSize(new java.awt.Dimension(1200, 600));
        centerPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(null);
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1200, 600));
        jScrollPane1.setViewportView(resultPanel);

        resultPanel.setAutoscrolls(true);
        resultPanel.setMaximumSize(new java.awt.Dimension(10000, 10000));
        resultPanel.setName(""); // NOI18N
        resultPanel.setLayout(new javax.swing.BoxLayout(resultPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(resultPanel);

        centerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        centerPanel.add(filtersPanel, java.awt.BorderLayout.WEST);

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public String getSearchTextFieldText() {
        return searchTextField.getText().trim();
    }

    public void addSearchButtonActionListener(ActionListener listener) {
        this.searchButton.addActionListener(listener);
    }
    
    public void addFilterButtonActionListener(ActionListener listener) {
        this.filterButton.addActionListener(listener);
    }
    
    public void addToResults(Component component) {
        this.resultPanel.add(component);
        this.resultPanel.validate();
    }
    
    public void emptyResults() {
        this.resultPanel.removeAll();
        this.revalidate();
    }
    
    public void toggleFiltersPanelVisible() {
        this.filtersPanel.setVisible(!filtersPanel.isVisible());
    }
    
    // FILTERS
    public FiltersPanel getFiltersPanel() {
        return this.filtersPanel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton filterButton;
    private com.iglnierod.gamearchive.view.home.search.FiltersPanel filtersPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchEastPanel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JPanel searchWestPanel;
    // End of variables declaration//GEN-END:variables
}
