/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iglnierod.gamearchive.view.home.community;

import java.awt.event.MouseListener;
import javax.swing.Icon;

/**
 *
 * @author iglnierod
 */
public class ActivityPanel extends javax.swing.JPanel {

    private String username;
    
    /**
     * Creates new form ActivityPanel
     */
    public ActivityPanel(String username) {
        this.username = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coverLabel = new javax.swing.JLabel();
        activityLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.controlDkShadow));
        setMaximumSize(new java.awt.Dimension(725, 175));
        setMinimumSize(new java.awt.Dimension(725, 175));

        coverLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NoImgAvaliable.png"))); // NOI18N

        activityLabel.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        activityLabel.setText("<html>Added game_name to <strong>list_name</strong></html>");

        dateLabel.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(204, 204, 204));
        dateLabel.setText("00/00/00 00:00");

        usernameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        usernameLabel.setText("<username>");
        usernameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(coverLabel)
                        .addGap(18, 18, 18)
                        .addComponent(activityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateLabel)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(usernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(activityLabel))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setUsernameLabelText(String username) {
        this.usernameLabel.setText(username);
    }

    public void setCoverLabelIcon(Icon cover) {
        this.coverLabel.setIcon(cover);
    }
    
    public void setCoverLabelToolTip(String gameName) {
        this.coverLabel.setToolTipText(gameName);
    }
    
    public void setActivityLabelText(String activity) {
        this.activityLabel.setText(activity);
    }
    
    public void setDateLabelText(String date) {
        this.dateLabel.setText(date);
    }
    
    public void addUsernameLabelMouseListener(MouseListener ml) {
        this.usernameLabel.addMouseListener(ml);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityLabel;
    private javax.swing.JLabel coverLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
