/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iglnierod.gamearchive.view.home;

import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JPanel;

/**
 *
 * @author iglnierod
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewHomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        myListsLabel = new javax.swing.JLabel();
        communityLabel = new javax.swing.JLabel();
        eastPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        gameCoverPanel1 = new com.iglnierod.gamearchive.view.game.panel.GameCoverPanel();
        gameCoverPanel2 = new com.iglnierod.gamearchive.view.game.panel.GameCoverPanel();
        gameCoverPanel3 = new com.iglnierod.gamearchive.view.game.panel.GameCoverPanel();
        gameCoverPanel4 = new com.iglnierod.gamearchive.view.game.panel.GameCoverPanel();
        gameCoverPanel5 = new com.iglnierod.gamearchive.view.game.panel.GameCoverPanel();
        gameCoverPanel6 = new com.iglnierod.gamearchive.view.game.panel.GameCoverPanel();
        gameCoverPanel7 = new com.iglnierod.gamearchive.view.game.panel.GameCoverPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        logOutMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();
        myListsMenu = new javax.swing.JMenu();
        reloadListsMenuItem = new javax.swing.JMenuItem();
        communityMenu = new javax.swing.JMenu();
        reloadActivityMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GameArchive");

        northPanel.setLayout(new java.awt.BorderLayout());

        searchLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        searchLabel.setText("Search");
        searchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        homeLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setText("Home");
        homeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        myListsLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        myListsLabel.setText("My Lists");
        myListsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        communityLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        communityLabel.setText("Community");
        communityLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(homeLabel)
                .addGap(18, 18, 18)
                .addComponent(searchLabel)
                .addGap(18, 18, 18)
                .addComponent(myListsLabel)
                .addGap(18, 18, 18)
                .addComponent(communityLabel)
                .addGap(27, 27, 27))
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLabel)
                    .addComponent(myListsLabel)
                    .addComponent(searchLabel)
                    .addComponent(communityLabel))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        northPanel.add(westPanel, java.awt.BorderLayout.WEST);

        usernameLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameLabel.setText("username");

        javax.swing.GroupLayout eastPanelLayout = new javax.swing.GroupLayout(eastPanel);
        eastPanel.setLayout(eastPanelLayout);
        eastPanelLayout.setHorizontalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eastPanelLayout.createSequentialGroup()
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        eastPanelLayout.setVerticalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eastPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(usernameLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        northPanel.add(eastPanel, java.awt.BorderLayout.EAST);

        getContentPane().add(northPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recommended games");

        jPanel2.add(gameCoverPanel1);
        jPanel2.add(gameCoverPanel2);
        jPanel2.add(gameCoverPanel3);
        jPanel2.add(gameCoverPanel4);
        jPanel2.add(gameCoverPanel5);
        jPanel2.add(gameCoverPanel6);
        jPanel2.add(gameCoverPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        centerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        logOutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logOutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/round_logout_white_24dp.png"))); // NOI18N
        logOutMenuItem.setText("Log out");
        fileMenu.add(logOutMenuItem);

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        quitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/round_close_white_24dp.png"))); // NOI18N
        quitMenuItem.setText("Quit");
        fileMenu.add(quitMenuItem);

        menuBar.add(fileMenu);

        myListsMenu.setText("My Lists");

        reloadListsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sync_24dp.png"))); // NOI18N
        reloadListsMenuItem.setText("Reload");
        myListsMenu.add(reloadListsMenuItem);

        menuBar.add(myListsMenu);

        communityMenu.setText("Community");

        reloadActivityMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sync_24dp.png"))); // NOI18N
        reloadActivityMenuItem.setText("Reload Activity");
        communityMenu.add(reloadActivityMenuItem);

        menuBar.add(communityMenu);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // ============ MENU BAR ============
    public void addLogOutMenuItemActionListener(ActionListener listener) {
        this.logOutMenuItem.addActionListener(listener);
    }

    public void addQuitMenuItemActionListener(ActionListener listener) {
        this.quitMenuItem.addActionListener(listener);
    }

    public void addReloadListsMenuItemActionListener(ActionListener listener) {
        this.reloadListsMenuItem.addActionListener(listener);
    }
    
    public void addReloadActivityListsMenuItemActionListener(ActionListener listener) {
        this.reloadActivityMenuItem.addActionListener(listener);
    }
    
    // ============ NAV VAR LISTENERS ============
    public void addHomeLabelMouseListener(MouseListener listener) {
        this.homeLabel.addMouseListener(listener);
    }

    public void addSearchLabelMouseListener(MouseListener listener) {
        this.searchLabel.addMouseListener(listener);
    }

    public void addMyListsLabelMouseListener(MouseListener listener) {
        this.myListsLabel.addMouseListener(listener);
    }

    public void addCommunityLabelMouseListener(MouseListener listener) {
        this.communityLabel.addMouseListener(listener);
    }

    public void addUsernameLabelMouseListener(MouseListener listener) {
        this.usernameLabel.addMouseListener(listener);
    }

    public void setUsernameLabelText(String username) {
        this.usernameLabel.setText(username);
    }
    
    //
    public void setCenterContent(JPanel panel) {
        this.centerPanel.removeAll();
        this.centerPanel.add(panel, BorderLayout.CENTER);
        this.centerPanel.revalidate();
        this.centerPanel.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel communityLabel;
    private javax.swing.JMenu communityMenu;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JMenu fileMenu;
    private com.iglnierod.gamearchive.view.game.panel.GameCoverPanel gameCoverPanel1;
    private com.iglnierod.gamearchive.view.game.panel.GameCoverPanel gameCoverPanel2;
    private com.iglnierod.gamearchive.view.game.panel.GameCoverPanel gameCoverPanel3;
    private com.iglnierod.gamearchive.view.game.panel.GameCoverPanel gameCoverPanel4;
    private com.iglnierod.gamearchive.view.game.panel.GameCoverPanel gameCoverPanel5;
    private com.iglnierod.gamearchive.view.game.panel.GameCoverPanel gameCoverPanel6;
    private com.iglnierod.gamearchive.view.game.panel.GameCoverPanel gameCoverPanel7;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem logOutMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel myListsLabel;
    private javax.swing.JMenu myListsMenu;
    private javax.swing.JPanel northPanel;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JMenuItem reloadActivityMenuItem;
    private javax.swing.JMenuItem reloadListsMenuItem;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables

}
