/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iglnierod.gamearchive.view.home;

import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JPanel;

/**
 *
 * @author iglnierod
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewHomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        myListsLabel = new javax.swing.JLabel();
        communityLabel = new javax.swing.JLabel();
        eastPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        logOutMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        northPanel.setLayout(new java.awt.BorderLayout());

        searchLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        searchLabel.setText("Search");
        searchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        homeLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setText("Home");
        homeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        myListsLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        myListsLabel.setText("My Lists");
        myListsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        communityLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        communityLabel.setText("Community");
        communityLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(homeLabel)
                .addGap(18, 18, 18)
                .addComponent(searchLabel)
                .addGap(18, 18, 18)
                .addComponent(myListsLabel)
                .addGap(18, 18, 18)
                .addComponent(communityLabel)
                .addGap(27, 27, 27))
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLabel)
                    .addComponent(myListsLabel)
                    .addComponent(searchLabel)
                    .addComponent(communityLabel))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        northPanel.add(westPanel, java.awt.BorderLayout.WEST);

        usernameLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        usernameLabel.setText("username");

        javax.swing.GroupLayout eastPanelLayout = new javax.swing.GroupLayout(eastPanel);
        eastPanel.setLayout(eastPanelLayout);
        eastPanelLayout.setHorizontalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eastPanelLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(usernameLabel)
                .addGap(38, 38, 38))
        );
        eastPanelLayout.setVerticalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eastPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(usernameLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        northPanel.add(eastPanel, java.awt.BorderLayout.EAST);

        getContentPane().add(northPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1224, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        centerPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        logOutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        logOutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/round_logout_white_24dp.png"))); // NOI18N
        logOutMenuItem.setText("Log out");
        fileMenu.add(logOutMenuItem);

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK));
        quitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/round_close_white_24dp.png"))); // NOI18N
        quitMenuItem.setText("Quit");
        fileMenu.add(quitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // ============ MENU BAR ============
    public void addLogOutMenuItemActionListener(ActionListener listener) {
        this.logOutMenuItem.addActionListener(listener);
    }

    public void addQuitMenuItemActionListener(ActionListener listener) {
        this.quitMenuItem.addActionListener(listener);
    }

    // ============ NAV VAR LISTENERS ============
    public void addHomeLabelMouseListener(MouseListener listener) {
        this.homeLabel.addMouseListener(listener);
    }

    public void addSearchLabelMouseListener(MouseListener listener) {
        this.searchLabel.addMouseListener(listener);
    }

    public void addMyListsLabelMouseListener(MouseListener listener) {
        this.myListsLabel.addMouseListener(listener);
    }

    public void addCommunityLabelMouseListener(MouseListener listener) {
        this.communityLabel.addMouseListener(listener);
    }

    public void addUsernameLabelMouseListener(MouseListener listener) {
        this.usernameLabel.addMouseListener(listener);
    }

    public void setUsernameLabelText(String username) {
        this.usernameLabel.setText(username);
    }
    
    //
    public void setCenterContent(JPanel panel) {
        this.emptyCenterContent();
        this.centerPanel.add(panel, BorderLayout.CENTER);
        this.centerPanel.revalidate();
    }

    private void emptyCenterContent() {
        this.centerPanel.removeAll();
    }
    
    public void addLogOutMenuItemActionListener(ActionListener listener) {
        this.logOutMenuItem.addActionListener(listener);
    }
    
    public void addQuitMenuItemActionListener(ActionListener listener) {
        this.quitMenuItem.addActionListener(listener);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel communityLabel;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logOutMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel myListsLabel;
    private javax.swing.JPanel northPanel;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables

}
