/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.iglnierod.gamearchive.view.home.list.dialog;

import com.iglnierod.gamearchive.view.game.panel.GameCoverPanel;
import com.iglnierod.gamearchive.view.layout.WrapLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionListener;

/**
 *
 * @author iglnierod
 */
public class ListDialog extends javax.swing.JDialog {

    /**
     * Creates new form ListDialog
     */
    public ListDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.centerPanel.setLayout(new WrapLayout(FlowLayout.LEFT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        southPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        counterLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        centerPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        optionsMenu = new javax.swing.JMenu();
        reloadMenuItem = new javax.swing.JMenuItem();
        editMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1110, 579));
        setMinimumSize(new java.awt.Dimension(1110, 579));

        nameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("This Is The List Title");

        javax.swing.GroupLayout northPanelLayout = new javax.swing.GroupLayout(northPanel);
        northPanel.setLayout(northPanelLayout);
        northPanelLayout.setHorizontalGroup(
            northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        northPanelLayout.setVerticalGroup(
            northPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        getContentPane().add(northPanel, java.awt.BorderLayout.NORTH);

        userLabel.setText("List by iglnierod");

        counterLabel.setText("Total games: 100");

        javax.swing.GroupLayout southPanelLayout = new javax.swing.GroupLayout(southPanel);
        southPanel.setLayout(southPanelLayout);
        southPanelLayout.setHorizontalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, southPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(counterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 885, Short.MAX_VALUE)
                .addComponent(userLabel)
                .addContainerGap())
        );
        southPanelLayout.setVerticalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, southPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(counterLabel))
                .addContainerGap())
        );

        getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(centerPanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        optionsMenu.setText("Options");

        reloadMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        reloadMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sync_24dp.png"))); // NOI18N
        reloadMenuItem.setText("Reload");
        optionsMenu.add(reloadMenuItem);

        editMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        editMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_24dp.png"))); // NOI18N
        editMenuItem.setText("Edit...");
        optionsMenu.add(editMenuItem);

        deleteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        deleteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/layers_clear_24dp.png"))); // NOI18N
        deleteMenuItem.setText("Delete");
        optionsMenu.add(deleteMenuItem);

        menuBar.add(optionsMenu);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void addReloadMenuItemActionListener(ActionListener l) {
        this.reloadMenuItem.addActionListener(l);
    }
    
    public void addEditMenuItemActionListener(ActionListener l) {
        this.editMenuItem.addActionListener(l);
    }

    public void addDeleteMenuItemActionListener(ActionListener l) {
        this.deleteMenuItem.addActionListener(l);
    }

    public void setNameLabelText(String name) {
        this.nameLabel.setText(name);
    }

    public void addGame(GameCoverPanel gamePanel) {
        this.centerPanel.add(gamePanel);
        this.revalidaCenterPanel();
    }

    public void revalidaCenterPanel() {
        this.centerPanel.revalidate();
        this.centerPanel.repaint();
    }

    public void removeAllGames() {
        this.centerPanel.removeAll();
        this.revalidaCenterPanel();
    }
    
    public void disableDeleteMenuItem() {
        this.deleteMenuItem.setEnabled(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel counterLabel;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem editMenuItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel northPanel;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenuItem reloadMenuItem;
    private javax.swing.JPanel southPanel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
