create table
  public.users (
    username text not null,
    email text not null,
    password text not null,
    created_at timestamp without time zone not null default now(),
    constraint users_pkey primary key (username)
  ) tablespace pg_default;
  
  create table
  public.games (
    id bigint generated by default as identity,
    checksum text not null,
    name text null,
    igdb_rating double precision null,
    rating_count bigint null,
    summary text null,
    artwork_id text null,
    cover_id text null,
    constraint games_pkey primary key (id)
  ) tablespace pg_default;
  
  create table
  public.genres (
    id bigint generated by default as identity,
    checksum text not null,
    name text null,
    constraint genres_pkey primary key (id)
  ) tablespace pg_default;
  
  create table
  public.companies (
    id bigint generated by default as identity,
    checksum text not null,
    logo_id text null,
    name text null,
    start_date date null,
    constraint companies_pkey primary key (id)
  ) tablespace pg_default;
  
  create table
  public.platforms (
    id bigint generated by default as identity,
    checksum text null,
    abbreviation text null,
    logo_id text null,
    name text null,
    constraint platforms_pkey primary key (id)
  ) tablespace pg_default;
  
  create table
  public.lists (
    created_at timestamp with time zone not null default now(),
    name text not null default ''::text,
    username text not null,
    description text null,
    id bigint generated by default as identity,
    constraint lists_pkey primary key (id),
    constraint public_lists_username_fkey foreign key (username) references users (username) on update cascade on delete cascade
  ) tablespace pg_default;
  
  create table
  public.lists_games (
    list_id bigint generated by default as identity,
    game_id bigint not null,
    created_at timestamp without time zone null default now(),
    constraint lists_games_pkey primary key (list_id, game_id),
    constraint public_lists_games_game_id_fkey foreign key (game_id) references games (id) on update cascade on delete cascade,
    constraint public_lists_games_list_id_fkey foreign key (list_id) references lists (id) on update cascade on delete cascade
  ) tablespace pg_default;
  
  create table
  public.games_companies (
    game_id bigint generated by default as identity,
    company_id bigint not null,
    constraint games_companies_pkey primary key (game_id, company_id),
    constraint public_games_companies_company_id_fkey foreign key (company_id) references companies (id) on update cascade on delete cascade,
    constraint public_games_companies_game_id_fkey foreign key (game_id) references games (id) on update cascade on delete cascade
  ) tablespace pg_default;
  
  create table
  public.games_genres (
    game_id bigint generated by default as identity,
    genre_id bigint not null,
    constraint games_genres_pkey primary key (game_id, genre_id),
    constraint public_games_genres_game_id_fkey foreign key (game_id) references games (id) on update cascade on delete cascade,
    constraint public_games_genres_genre_id_fkey foreign key (genre_id) references genres (id) on update cascade on delete cascade
  ) tablespace pg_default;
  
  create table
  public.platforms_games (
    platform_id bigint generated by default as identity,
    game_id bigint not null,
    constraint platforms_games_pkey primary key (platform_id, game_id),
    constraint public_platforms_games_game_id_fkey foreign key (game_id) references games (id) on update cascade on delete cascade,
    constraint public_platforms_games_platform_id_fkey foreign key (platform_id) references platforms (id) on update cascade on delete cascade
  ) tablespace pg_default;
  
  create table
  public.ratings (
    username text not null,
    game_id bigint not null,
    rating double precision not null,
    note text not null,
    created_at timestamp without time zone not null default now(),
    constraint ratings_pkey primary key (username, game_id),
    constraint public_ratings_game_id_fkey foreign key (game_id) references games (id) on update cascade on delete cascade,
    constraint public_ratings_username_fkey foreign key (username) references users (username) on update cascade on delete cascade
  ) tablespace pg_default;
  
  create table
  public.users_platforms (
    username text not null,
    platform_id bigint not null,
    constraint users_platforms_pkey primary key (username, platform_id),
    constraint public_users_platforms_platform_id_fkey foreign key (platform_id) references platforms (id) on update cascade on delete cascade,
    constraint public_users_platforms_username_fkey foreign key (username) references users (username) on update cascade on delete cascade
  ) tablespace pg_default;
  