/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iglnierod.gamearchive.view.client;

import java.awt.event.MouseListener;

/**
 *
 * @author iglnierod
 */
public class ClientPreviewPanel extends javax.swing.JPanel {

    /**
     * Creates new form GamePreview
     */
    private final String USERNAME;

    public ClientPreviewPanel(String username) {
        initComponents();
        this.USERNAME = username;
        this.setUsernameLabelText(this.USERNAME);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(80, 82, 84), 1, true));
        setForeground(new java.awt.Color(221, 221, 221));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(475, 156));
        setMinimumSize(new java.awt.Dimension(475, 156));
        setPreferredSize(new java.awt.Dimension(475, 156));

        usernameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        usernameLabel.setText("username");
        usernameLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        usernameLabel.setFocusable(false);
        usernameLabel.setMaximumSize(new java.awt.Dimension(30, 150));
        usernameLabel.setMinimumSize(new java.awt.Dimension(30, 150));
        usernameLabel.setPreferredSize(new java.awt.Dimension(30, 150));

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        descriptionTextArea.setEnabled(false);
        descriptionTextArea.setFocusable(false);
        scrollPane.setViewportView(descriptionTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPane)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void addPanelMouseListener(MouseListener l) {
        this.addMouseListener(l);
        this.usernameLabel.addMouseListener(l);
        this.descriptionTextArea.addMouseListener(l);
    }

    public void setUsernameLabelText(String username) {
        this.usernameLabel.setText(username);
    }

    public void setDescriptionTextAreaText(String description) {
        this.descriptionTextArea.setText(description);
    }

    public String getUsername() {
        return this.USERNAME;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
